﻿using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;


namespace Csra {

    /// <summary>
    /// Class to parse information from an ssn.csv file. Only for use in constructor method of <see cref="ScanNetworkPatternInfo"/>.
    /// </summary>
    [Serializable]
    public class SsnCsvFile {

        #region Properties

        private string _csvFileName = string.Empty;
        /// <summary>
        /// The version of the ssn setup csv file.
        /// It shall appear in the first line of the csv file, which starts with "//SSN instances". Default to "v1.0" if not specified.
        /// </summary>
        public string CsvVersion { get; private set; } = string.Empty;

        private const string _defaultVersion = "v1.0";
        private const string _version2025_7 = "v2025.7";

        /// <summary>
        /// The pin list is used for modifying the disable-contribution-bits in the ssn_setup pattern.
        /// </summary>
        public string ContribPin {
            get {
                var instancesWithContribPin = SshInstances.Values.Where(ssh => ssh.ContainsKey("Contrib pin"));
                var contribPinValues = instancesWithContribPin.Select(ssh => ssh["Contrib pin"]);
                var uniqueContribPins = contribPinValues.Distinct();
                return string.Join(",", uniqueContribPins);
            }
        }

        /// <summary>
        /// The label is used for modifying the disable-contribution-bits in the ssn_setup pattern.
        /// </summary>
        public string ContribLabel { get; private set; } = null;

        /// <summary>
        /// The pin list that output the sticky bits in the ssn end pattern.
        /// </summary>
        public string StickyPin {
            get {
                var instancesWithStickyPin = SshInstances.Values.Where(ssh => ssh.ContainsKey("Sticky pin"));
                var stickyPinValues = instancesWithStickyPin.Select(ssh => ssh["Sticky pin"]);
                var uniqueStickyPins = stickyPinValues.Distinct();
                return string.Join(",", uniqueStickyPins);
            }
        }

        /// <summary>
        /// The TCK ratio of the SSN pattern. It is used to determine the number of vectors to be modified for each disable-contribution-bit in the ssn_setup
        /// pattern. In v1.0, the attribute name was "Num bits", in v2025.7 it is changed to "Tck ratio".
        /// </summary>
        public string TckRatio { get; private set; } = null;

        /// <summary>
        /// Dictionary of SSH instances,
        /// where the default Attribute for key is the icl-instance name and the value is a dictionary of attribute names and values.
        /// </summary>
        public Dictionary<string, Dictionary<string, string>> SshInstances { get; } = [];

        /// <summary>
        /// The attribute name used as the key for indexing instances.
        /// </summary>
        public string InstanceKey { get; private set; } = "Ssh instance";

        internal int KeyIdx;
        #endregion

        #region Constructors

        /// <summary>
        /// Default constructor for serialization only. It's useful for UT!
        /// </summary>
        internal SsnCsvFile() {
        }

        /// <summary>
        /// Construct a new <see cref="SsnCsvFile"/> object and load the specified _ssn.csv file.
        /// </summary>
        /// <param name="fileName">The _ssn.csv file name, which is generated by ATEGEN along with the atp file.</param>
        /// <param name="instanceKey">Optional. The <c>Key</c> attribute for indexing the instances. Must be an attribute whose value is unique across all
        /// instances. By default it's the 3rd column, which is "Ssh instance".</param>
        public SsnCsvFile(string fileName, string instanceKey = "Ssh instance") {
            _csvFileName = fileName;
            try {
                string[] lines = ReadAllLines(fileName);
                CsvVersion = GetVersion(lines);
                Dictionary<string, int> indicesOfAttributes = GetAttributeIndices(lines, instanceKey);
                Dictionary<string, Action<string>> patternAttributeSetters = GetPatternAttributeSetters();
                Dictionary<string, Action<string, string>> iclInstanceAttributeSetters = GetInstanceAttributeSetters();

                // Parse each line that contains valid instance info with attributeSetters
                string[] validInstances = [.. lines.Where(line => !string.IsNullOrWhiteSpace(line) && !line.TrimStart().StartsWith("//"))];
                foreach (string instanceInfo in validInstances) {
                    AppendSshInstance(instanceInfo, indicesOfAttributes, patternAttributeSetters, iclInstanceAttributeSetters);
                }
            } catch (Exception ex) {
                CsvVersion = string.Empty;
                ContribLabel = string.Empty;
                TckRatio = string.Empty;
                SshInstances.Clear();
                Api.Services.Alert.Warning($"Failed to process SSN CSV file '{fileName}'. Exception: {ex.Message}");
            }
        }

        /// <summary>
        /// Read all lines from the csv file.
        /// </summary>
        /// <param name="fileName">Absolute file name with path.</param>
        /// <returns>all the lines in file if succeed.</returns>
        /// <exception cref="InvalidDataException">file contains zero lines.</exception>
        internal string[] ReadAllLines(string fileName) {
            string[] lines = File.ReadAllLines(fileName);
            if (lines.Length == 0) {
                throw new InvalidDataException($"CSV file '{fileName}' is empty.");
            }
            return lines;
        }

        /// <summary>
        /// Get csv version from the first line. Default to "v1.0" if not specified.
        /// </summary>
        /// <param name="lines">File lines</param>
        /// <returns>Version string</returns>
        internal string GetVersion(string[] lines) {
            string csvFileVersionMarker = "//SSN instances";
            string[] versionString = lines[0].Split([','], 2, StringSplitOptions.None);
            if (versionString[0].TrimStart().StartsWith(csvFileVersionMarker))
                return versionString[1].Trim();
            else
                return _defaultVersion;    // Default version if not specified.
        }

        /// <summary>
        /// Get header information from the first line that starts with "//ID," and store as the attribute indices.
        /// </summary>
        /// <param name="lines">File lines</param>
        /// <param name="instanceKey">The name of the attribute used as key for indexing the instances.</param>
        /// <returns>Indices of attributes</returns>
        /// <remarks>Different versions may have different header formats.</remarks>
        /// <exception cref="InvalidDataException">The specified attribute as key for indexing instances not found in the CSV header.</exception>
        internal Dictionary<string, int> GetAttributeIndices(string[] lines, string instanceKey) {
            string csvFileHeaderMarker = "//ID,";
            Dictionary<string, int> indicesOfAttributes = [];
            foreach (string line in lines) {
                if (line.StartsWith(csvFileHeaderMarker)) {
                    string[] header = line.Split([','], StringSplitOptions.None);
                    header[0] = header[0].Trim('/');
                    indicesOfAttributes = header.ToDictionary(attribute => attribute.Trim(), attribute => Array.IndexOf(header, attribute));
                    if (indicesOfAttributes.TryGetValue(instanceKey, out KeyIdx)) {
                        InstanceKey = instanceKey;
                    } else if (indicesOfAttributes.TryGetValue(InstanceKey, out KeyIdx)) {
                        // The specified instance key attribute not found, default to "Ssh instance". This could be a typo by user, alert user with warning.
                        Api.Services.Alert.Warning($"The specified attribute '{instanceKey}' as key for indexing instances not found in the CSV header. " +
                            $"Defaulting to '{InstanceKey}' as the instance key.");
                    } else {
                        // Neither the specified instance key attribute nor the default "Ssh instance" found in the header, use the first attribute as key.
                        Api.Services.Alert.Warning($"Default instance key attribute '{InstanceKey}' not found in the CSV header either. Fall back to use " +
                            $"'{indicesOfAttributes.FirstOrDefault().Key}' instead.");
                        InstanceKey = indicesOfAttributes.FirstOrDefault().Key;
                        KeyIdx = indicesOfAttributes.FirstOrDefault().Value;
                    }
                    break;  // Header found, exit loop.
                }
            }
            return indicesOfAttributes;
        }

        internal Dictionary<string, Action<string>> GetPatternAttributeSetters() {
            // value-uniformed attributes in all csv versions
            string contribLabelAttributeName = "Contrib label";
            string tckRatioAttributeName = CsvVersion == _defaultVersion ? "Num bits" : "Tck ratio";
            var patternAttributeSetters = new Dictionary<string, Action<string>> {
                { contribLabelAttributeName,    value => SetPatternAttribute(nameof(ContribLabel), value, contribLabelAttributeName) },
                { tckRatioAttributeName,        value => SetPatternAttribute(nameof(TckRatio), value, tckRatioAttributeName) }
            };
            return patternAttributeSetters;
        }

        internal Dictionary<string, Action<string, string>> GetInstanceAttributeSetters() {
            string idAttributeName = "ID";
            string coreInstanceAttributeName = "Core instance";
            string sshInstanceAttributeName = "Ssh instance";
            string iclInstanceAttributeName = "Icl instance";
            string groupIdAttributeName = "Group ID";
            string contribPinAttributeName = "Contrib pin";
            string contribOffsetAttributeName = "Contrib offset";
            string stickyPinAttributeName = "Sticky pin";
            string stickyLabelAttributeName = "Sticky label";
            string stickyOffsetAttributeName = "Sticky offset";
            string stickyCycleAttributeName = "Sticky cycle";

            // Version 2025.7 specific attributes
            string onChipCompareAttributeName = "On chip compare";
            string representativeSshAttributeName = "Representative ssh";
            string perChainStickyPinAttributeName = "Per chain sticky pin";
            string perChainStickyLabelAttributeName = "Per chain sticky label";
            string perChainStickyNBitsAttributeName = "Per chain sticky nbits";
            string chain0StickyOffsetAttributeName = "Chain0 sticky offset";
            string chain0StickyCycleAttributeName = "Chain0 sticky cycle";

            var iclInstanceAttributeSetters = new Dictionary<string, Action<string, string>> {
                {idAttributeName,              (instanceID, value) => SetInstanceAttribute(instanceID, idAttributeName, value, true) },
                {coreInstanceAttributeName,    (instanceID, value) => SetInstanceAttribute(instanceID, coreInstanceAttributeName, value, false) },
                {sshInstanceAttributeName,     (instanceID, value) => SetInstanceAttribute(instanceID, sshInstanceAttributeName, value, true) },
                {iclInstanceAttributeName,     (instanceID, value) => SetInstanceAttribute(instanceID, iclInstanceAttributeName, value, true) },
                {groupIdAttributeName,         (instanceID, value) => SetInstanceAttribute(instanceID, groupIdAttributeName, value, false) },
                {contribPinAttributeName,      (instanceID, value) => SetInstanceAttribute(instanceID, contribPinAttributeName, value, false) },
                {contribOffsetAttributeName,   (instanceID, value) => SetInstanceAttribute(instanceID, contribOffsetAttributeName, value, true) },
                {stickyPinAttributeName,       (instanceID, value) => SetInstanceAttribute(instanceID, stickyPinAttributeName, value, false) },
                {stickyLabelAttributeName,     (instanceID, value) => SetInstanceAttribute(instanceID, stickyLabelAttributeName, value, false) },
                {stickyOffsetAttributeName,    (instanceID, value) => SetInstanceAttribute(instanceID, stickyOffsetAttributeName, value, false) },
                {stickyCycleAttributeName,     (instanceID, value) => SetInstanceAttribute(instanceID, stickyCycleAttributeName, value, true) },
            };
            if (CsvVersion.StartsWith(_version2025_7)) {
                var versionSpecificSetters = new Dictionary<string, Action<string, string>> {
                    {onChipCompareAttributeName,      (instanceID, value) => SetInstanceAttribute(instanceID, onChipCompareAttributeName, value, false)},
                    {representativeSshAttributeName,  (instanceID, value) => SetInstanceAttribute(instanceID, representativeSshAttributeName, value, false)},
                    {perChainStickyPinAttributeName,  (instanceID, value) => SetInstanceAttribute(instanceID, perChainStickyPinAttributeName, value, false)},
                    {perChainStickyLabelAttributeName,(instanceID, value) => SetInstanceAttribute(instanceID, perChainStickyLabelAttributeName, value, false)},
                    {perChainStickyNBitsAttributeName,(instanceID, value) => SetInstanceAttribute(instanceID, perChainStickyNBitsAttributeName, value, false)},
                    {chain0StickyOffsetAttributeName, (instanceID, value) => SetInstanceAttribute(instanceID, chain0StickyOffsetAttributeName, value, true)},
                    {chain0StickyCycleAttributeName,  (instanceID, value) => SetInstanceAttribute(instanceID, chain0StickyCycleAttributeName, value, true)}
                };
                foreach (var setter in versionSpecificSetters) {
                    iclInstanceAttributeSetters.Add(setter.Key, setter.Value);
                }
            }
            return iclInstanceAttributeSetters;
        }

        /// <summary>
        /// Appends an SSH instance by parsing its attributes and setting them accordingly.
        /// </summary>
        /// <param name="instanceInfo">A line read from the csv file for parsing.</param>
        /// <param name="instanceKey">The attribute name used as the key for indexing instances.</param>
        /// <param name="indicesOfAttributes">Header of the attribute table that maps attribute names to their column indices.</param>
        /// <param name="patternAttributeSetters">Dictionary mapping pattern attribute names to their setter Actions.</param>
        /// <param name="iclInstanceAttributeSetters">Dictionary mapping instance attribute names to their setter Actions.</param>
        internal void AppendSshInstance(string instanceInfo, Dictionary<string, int> indicesOfAttributes,
            Dictionary<string, Action<string>> patternAttributeSetters, Dictionary<string, Action<string, string>> iclInstanceAttributeSetters) {
            var attributes = instanceInfo.Split([','], StringSplitOptions.None);
            if (attributes.Length != indicesOfAttributes.Count) {
                Api.Services.Alert.Warning($"The number of attributes ({attributes.Length}) in the line '{instanceInfo}' does not match the expected " +
                    $"count ({indicesOfAttributes.Count}) from the header in the CSV file [{_csvFileName}]. This line will be skipped.");
                return;
            }

            // Apply pattern attribute setters.
            SetAndCheckAttributes(patternAttributeSetters, (setter, value) => setter(value));

            // Apply instance-specific attribute setters.
            string instanceID = attributes[KeyIdx].Trim();
            SetAndCheckAttributes(iclInstanceAttributeSetters, (setter, value) => setter(instanceID, value));

            // Local function to set and check attributes using provided setters.
            void SetAndCheckAttributes<T>(Dictionary<string, T> setters, Action<T, string> applySetter) {
                foreach (var attributeName in setters.Keys) {
                    if (indicesOfAttributes.TryGetValue(attributeName, out int index) && index < attributes.Length) {
                        string attributeValue = attributes[index].Trim();
                        applySetter(setters[attributeName], attributeValue);
                    }
                }
            }
        }

        /// <summary>
        /// Helper method to set properties by name, check for consistency as well.
        /// </summary>
        /// <param name="attributePropertyName">Name of the Property to update/check</param>
        /// <param name="attributeValue">Value of the Property to update/check</param>
        /// <param name="propertyDisplayName">Display name of the Property, for reporting exceptions.</param>
        /// <exception cref="InvalidDataException">Value inconsistent, check csv file is recommended.</exception>
        internal void SetPatternAttribute(string attributePropertyName, string attributeValue, string propertyDisplayName) {
            if (!string.IsNullOrEmpty(attributeValue)) {
                var property = GetType().GetProperty(attributePropertyName, System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public |
                    System.Reflection.BindingFlags.NonPublic);
                var currentValue = property?.GetValue(this) as string;
                if (string.IsNullOrEmpty(currentValue)) {
                    property?.SetValue(this, attributeValue);
                } else if (currentValue != attributeValue) {
                    // New value is different from existing, discard the new value and alert user with warning.
                    Api.Services.Alert.Warning($"{propertyDisplayName} is already set to a different value. Existing value is '{currentValue}', the new value " +
                        $"'{attributeValue}' will be discarded. Please check the csv file [{_csvFileName}].");
                }
            }
        }

        /// <summary>
        /// Helper method to set per-instance attributes with optional uniqueness check.
        /// </summary>
        /// <param name="iclInstance"></param>
        /// <param name="attributeName">Name of the attribute to update/check</param>
        /// <param name="attributeValue">New value of the attribute to be updated/checked</param>
        /// <param name="enforceUniqueValue">Check for duplicated values across instances.</param>
        /// <exception cref="InvalidDataException">Invalid attribute values found in the csv file.</exception>
        internal void SetInstanceAttribute(string iclInstance, string attributeName, string attributeValue, bool enforceUniqueValue) {
            // skipping empty values
            if (!string.IsNullOrEmpty(attributeValue)) {
                if (!SshInstances.ContainsKey(iclInstance)) {
                    // Instance does not exist yet, initialize a new instance entry.
                    SshInstances[iclInstance] = [];
                } else if (SshInstances[iclInstance].TryGetValue(attributeName, out string currentValue)) {
                    // Attribute already exists for this instance, check for consistency
                    if (currentValue != attributeValue) {
                        // New value is different from existing, discard the new value and alert user with warning.
                        Api.Services.Alert.Warning($"{attributeName} is already set to a different value for instance [{iclInstance}]. Existing value is " +
                            $"'{currentValue}', the new value '{attributeValue}' will be discarded. Please check the csv file [{_csvFileName}].");
                    }
                    // No change is needed.
                    return;
                }
                // Instance is new or attribute does not exist yet. Either way, add attribute value to the instance.
                if (!enforceUniqueValue) {
                    // Attribute does not enforce value to be unique across instances, skip the check and add the attribute and value directly.
                    SshInstances[iclInstance][attributeName] = attributeValue;
                } else if (!SshInstances.Values.Any(instance => instance.TryGetValue(attributeName, out string existingValue) &&
                  existingValue == attributeValue)) {
                    // Unique value check passed across all instances for this property. Add the attribute and value to the instance.
                    SshInstances[iclInstance][attributeName] = attributeValue;
                } else {
                    // Unique value check failed, Value should be unique but is not, discard the new value and warn user.
                    Api.Services.Alert.Warning($"Value for attribute [{attributeName}] of instance [{iclInstance}] is not unique. This indicates that " +
                        $"the csv file has duplicate <{attributeName}> values for different ssh-icl-instance. The value '{attributeValue}' for attribute " +
                        $"<{attributeName}> of instance [{iclInstance}] will be discarded. Please check the csv file [{_csvFileName}].");
                }
            }
        }
        #endregion
    }
}